= BI-WSI-SI-8
:stem:
:imagesdir: images

== Základní pojmy

* *Třída* – Vzor pro objekt. Definuje vlastnosti a chování objektů
vytvářených podle tohoto vzoru.
* *Objekt* – Instance třídy. Uchovává svůj vlastní vnitřní stav. Má
vlastní identifikátor, kterým se odlišuje od ostatních objektů stejné
třídy (objekt je vždy jedinečný v rámci programu).
+
Chování objektu (_behaviour_) je definované jeho třídou. Objekt reaguje
na zasílané zprávy (_messages_) tak, že provede příslušnou metodu
definovanou pro jeho třídu (*method lookup*).
+
Objekt má zodpovědnost: sadu problémů, které řeší. (viz. *distribution
of responsibility*, *separation of concerns*).
** *atributy* – udržují vnitřní stav objektu
** *metody* – využívají nebo mění vnitřní stav objektu
* *Zpráva (Message)* – _What to do?_
+
Zpráva odeslaná cílovému objektu, aby něco provedl. Různí příjemci mohou
reagovat na stejnou zprávu různě. Příjemce je známý až při chodu
programu (*late binding*).
* *Metoda (Method)* – _How to do it?_
+
Sekvence instrukcí pro vyřešení problému. Definice, jak odpovědět na
zprávu. Jakou metodu vybrat při danné zprávě se určuje dynamicky za běhu
programu (*late binding*) podle procesu *method lookup*.

== OOP foundations

Základy pro objektově orientované paradigma.

=== Abstrakce

Objekt vytváří určitou abstrakci, která schovává interní implementaci a
detaily před ostatními objekty. _Ostatní objekty mohou s konkrétním
objektem komunikovat pouze zasíláním zpráv a nesmějí vědět, jak
konkrétní objekt funguje uvnitř_.

=== Encapsulation

_information hiding, zapouzdření_

Vnitřní stav objektu není přístupný zvenčí. Stav objektu je udržován
pomocí jeho atributů. Ty lze měnit a číst pouze pomocí metod. Tím má
objekt větší kontrolu nad změnami svého stavu.

=== Composition

Třída může být závislá na jednom či více jiných objektech. To má za
následek:

* delegování problémů na jiné objekty pro lepší znovupoužitelnost kódu,
* výměna implementace dílčího objektu nijak neovlivní chování objektu,
který s ním pracuje.

=== Distribution of responsibility

_separation of concerns_

Rozdělení zodpovědnosti (funkcionality nebo chování) mezi objekty tak,
aby se co nejméně překrývaly (aby implementace zabrala co nejméně kódu,
tedy znovupoužitelnost kódu byla co nejvyšší).

=== Message passing

_delegating responsibility_

Delegování zodpovědoností na dílčí objekty. Vyhodnocování metody objektu
(_receiver_) v kontextu jiného objektu (_sender_).

* *explicit* – Předání _sender_ objektu do _receiver_ objektu.
* *implicit* – _Receiver_ objekt provede _method lookup_ podle zaslané
zprávy (Pharo).

=== Inheritance

Zakládání vlastností jedné třídy (_child class_, _derived class_ nebo
_subclass_) na jiné nadřazené třídě (_parent class_, _base class_ nebo
_super class_). Mezi třídami pak vzniká stromová hierarchie. _Sub class_
získává všechny vlastnosti svojí _super class_ a přidává nové.

==== Polymorphism

Jednotné rozhraní pro různé datové typy objektů. _K objektům různých
typů lze přistupovat pomocí jednoho rozhraní_. Dynamický polymorfismus:
Jaký konkrétní objekt se použije se vybere až za běhu programu (*late
binding*).

== OOP foundations ideas

=== Uniform reference

Všechno je objekt. Každá entita OO programu je objekt.

=== Uniform access

Všechno se provádí pouze pomocí zasílání zpráv mezi objekty.
