= BI-SPOL-2
:stem:
:imagesdir: images

== Regulární jazyky

Libovolný jazyk je regulární, právě když je přijímaný konečným automatem

=== Deterministické automaty

*Deterministický* konečný automat je pětice
latexmath:[$M=(Q,\Sigma,\delta,q_0,F)$], kde

* latexmath:[$Q$] - konečná množina stavů
* latexmath:[$\Sigma$] - konečná abeceda
* latexmath:[$\delta$] - zobrazení latexmath:[$Q\times\Sigma \to Q$]
* latexmath:[$q_0$] - počáteční stav
* latexmath:[$F\subseteq Q$] - množina koncových stavů

* *Konfigurace* konečného automatu latexmath:[$M$] (viz výše) je
** dvojice latexmath:[$(q,w)\in Q\times \Sigma^{*}$].
** počáteční - latexmath:[$(q_0,w)$]
** koncová - latexmath:[$(q,\varepsilon)$], kde latexmath:[$q\in F$]
* *Přechod* latexmath:[$\vdash_M$] je relace nad
latexmath:[$Q\times\Sigma^{*}$], taková, že
latexmath:[$(q, w) \vdash_M (p, w')$] právě tehdy, když
latexmath:[$w = aw'$] a latexmath:[$\delta(q, a) = p$] pro nějaké
latexmath:[$a\in\Sigma,w \in \Sigma{*}.$]
* Jazyk *je přijímaný* DKA automatem latexmath:[$M$], jestliže existuje
přechod z latexmath:[$q_0$] do latexmath:[$q\in F$].
* DKA nazveme *úplně úrčený*, když je zobrazení
latexmath:[$\delta(q,a)$] definováno pro všechny dvojice stavů a
vstupních symbolů.

=== Nedeterministické automaty

*Nedeterministický* konečný automat je pětice
latexmath:[$M=(Q,\Sigma,\delta,q_0,F)$], kde

* latexmath:[$\delta$] - zobrazení latexmath:[$Q\times\Sigma$] do
množiny všech podmnožin latexmath:[$Q$].

Stav latexmath:[$q\in Q$] je *dosažitelný*, pokud
latexmath:[$\exists w\in\Sigma^{*}: (q_0,w)\vdash^{*}(q,\varepsilon)$].
Jinak je stav nedosažitelný.

Stav latexmath:[$q\in Q$] je *užitečný*, pokud
latexmath:[$\exists w\in\Sigma^{*},\exists p\in F: (q,w)\vdash^{*}(p,\varepsilon)$].
Jinak je stav zbytečný.

== Determinizace konečného automatu

Pro každý NKA platí, že k němu existuje ekvivaletní DKA.

Jako příklad uvedeme NKA:

Determinizaci začneme odstraněním počátečních stavů a jejich nahrazení
jedním počátečním stavem.

== Minimalizace deterministického konečného automatu

TODO

== Operace s konečnými automaty

* Sjednocení - latexmath:[$L(M) = L(M1) \cup L(M2)$]
* Průnik - latexmath:[$L(M) = L(M1) \cap L(M2)$]
* Doplněk - Úplně určený DKA, latexmath:[$F'=Q\setminus F$]
* Součin - ke koncovému stavu latexmath:[$M_1$] přidáme počáteční stav
latexmath:[$M_2$]; latexmath:[$q_{0,M}=q_{0,M_1}, F_M=F_2$]
* Iterace - vytvoříme latexmath:[$q_0$], který bude zároveň koncový a ze
všech původních koncových stavů povede latexmath:[$\varepsilon$] přechod
do počátečního stavu latexmath:[$q_0$].

== Regulární gramatiky

Gramatika latexmath:[$G=(N,\Sigma,P,S)$] je *regulární*, jestliže každé
pravidlo má tvar latexmath:[$A \to aB$] nebo latexmath:[$A \to a$], kde
latexmath:[$A, B \in N, a \in \Sigma$], nebo tvar
latexmath:[$S \to \varepsilon$] v případě, že latexmath:[$S$] se
nevyskytuje na pravé straně žádného pravidla.

== Regulární výrazy

*Regulární výraz* latexmath:[$V$] nad abecedou latexmath:[$\Sigma$] je
definován následujícím způsobem:

[arabic]
. latexmath:[$\emptyset, \varepsilon, a$] jsou regulární výrazy pro
všechna latexmath:[$a \in\Sigma$].
. Jsou-li latexmath:[$x, y$] regulární výrazy nad latexmath:[$\Sigma$],
pak:

* latexmath:[$(x + y)$] (sjednocení, alternativa),
* latexmath:[$(x.y)$] (zřetězení) a
* latexmath:[$(x)^*$] (iterace)

jsou regulární výrazy nad latexmath:[$\Sigma$].

== Regulární rovnice

Standardní soustava *regulárních rovnic* má tvar:
latexmath:[$X_i = \alpha_{i0} + \alpha_{i1}X_1 + \alpha_{i2}X_2 + \cdots + \alpha_{in}X_n, 1 \leq i \leq n$],
kde latexmath:[$X_1, X_2, \dots , X_n$] jsou neznámé a
latexmath:[$\alpha_{ij}$] jsou regulární výrazy nad abecedou
latexmath:[$\Sigma$], která neobsahuje
latexmath:[$X_1, X_2, \dots , X_n$].
